spring.data.mongodb.uri=mongodb://localhost:2717/RideSharing
spring.data.mongodb.database=RideSharing

server.servlet.context-path=/passenger
server.port=8091

secret.key=mySuperSecretKey12345678901234567890123456789012

kafka.bootstrap-servers=localhost:19092
schema.registry.url=http://localhost:8081
